# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Polhill
email: JohnPolhill42@gmail.com
url: https://JohnP42.github.io
profile: img/profile.png
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Web Developer - Programmer - Game Developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnp42.github.io" # the base hostname & protocol for your site
github_username:  JohnP42

contact: static

# Build settings
markdown: kramdown

color:
  primary: B81D18 #B81D18
  primary-rgb: "184,29,24" #"184,29,24"
  secondary: 202020 #202020
  secondary-dark: 101010 #101010

footer:
  copyright: John Polhill
  location: Location
  social: Social Media

social:
  - title: linkedin
    url: https://www.linkedin.com/in/jpolhill
  - title: facebook
    url: https://www.facebook.com/john.polhill.3
  - title: github
    url: https://github.com/JohnP42

address:
  - line: Chicago
